### ISSUE TITLE
Support injection via arrays

### ISSUE THREAD

**Issue by CookieNick** [Barsonax/Singularity#121]
Currently, it can inject into `IEnumerable`, but it can't in an array. So if you got, for example, an constructor like;

```cs
public CookieBaker(Ingredient[] ingredients)
```

It won't work. I wanted to implement my own `IServiceBindingGenerator` based on the `EnumerableServiceBindingGenerator`, but stuff like `ExpressionGenerator.ScopeParameter` and `BindingMetadata.GeneratedInstance` are internal so it's not feasible within my own project.

Final goal is to use this to implement a dynamic decorator using using the Castle DynamicProxy, which generates a new constructor which expects `IInterceptor[]`.

I've worked around it by doing;
```cs
var container = new Container(b =>
{
	var interceptors = new IInterceptor[] { new TestInterceptor() };
	b.Register<IInterceptor[]>(c => c.Inject(() => interceptors));

	b.Register<ITestInterface, TestClass>();

        var proxyType = ProxyBuilder.CreateInterfaceProxyTypeWithTargetInterface(typeof(ITestInterface), Array.Empty<Type>(), ProxyGenerationOptions.Default);
	b.Decorate(typeof(ITestInterface), proxyType);
});
```

It works in my use case because I don't need IoC in my interceptor, but I might imagine there are more elegant ways to solve this.

**Comment by Barsonax** [comment]
> Currently, it can inject into IEnumerable, but it can't in an array. So if you got, for example, an constructor like;

Yes this is true as I only implemented these for the readonly interfaces for now. Its not hard to modify singularity to do it for arrays, lists etc as well though so I added support for these in this branch: https://github.com/Barsonax/Singularity/tree/feature/morecollectionssupport

After some more testing/cleanup I will merge this and release a new version.

> It won't work. I wanted to implement my own IServiceBindingGenerator based on the EnumerableServiceBindingGenerator, but stuff like ExpressionGenerator.ScopeParameter and BindingMetadata.GeneratedInstance are internal so it's not feasible within my own project.

This scenario is till something I have to test more (hence the preview status) and make sure everything is public that needs to be public.

**Comment by Barsonax** [comment]
Singularity v0.16 can now inject more collection types such as arrays
