### ISSUE TITLE
Null exception error

### ISSUE THREAD

**Issue by Olbrasoft** [Barsonax/Singularity#141]
Sorry I don't speak English well 

Register services by Singularity error viz video https://youtu.be/-hcqYX_ZwyM

 by Microsoft OK and by LightInject OK

Repository is https://github.com/Olbrasoft/Blog

Singularity.Container.GetInstance(Type type, Scoped scope)
Singularity.Scoped.System.IServiceProvider.GetService(Type serviceType)
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<T>(IServiceProvider provider)
Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache+<>c__DisplayClass4_0.<GetOrAdd>g__BuildServiceProvider|3()
Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache+<>c__DisplayClass4_0.<GetOrAdd>b__2(long k)
System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, bool providerRequired)
Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUserContext<TUser, TKey, TUserClaim, TUserLogin, TUserToken>..ctor(DbContextOptions options)
Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext<TUser, TRole, TKey, TUserClaim, TUserRole, TUserLogin, TRoleClaim, TUserToken>..ctor(DbContextOptions options)
Olbrasoft.Blog.Data.EntityFrameworkCore.BlogDbContext..ctor(DbContextOptions options) in BlogDbContext.cs
+
        public BlogDbContext(DbContextOptions options) : base(options)
(Closure<Func<Scoped, DbContextOptions>> , Scoped )
Singularity.Scoped.GetOrAddScopedInstance<T>(Func<Scoped, T> factory, Type key)
(Closure<Func<Scoped, BlogDbContext>, Func<Scoped, IdentityErrorDescriber>> , Scoped )
Singularity.Scoped.GetOrAddScopedInstance<T>(Func<Scoped, T> factory, Type key)
(Closure<Func<Scoped, UserStore<BlogUser, BlogRole, BlogDbContext, int, BlogUserClaim, BlogUserToRole, BlogUserLogin, BlogUserToken, BlogRoleClaim>>, OptionsManager<IdentityOptions>, Func<Scoped, PasswordHasher<BlogUser>>, Func<Scoped, IUserValidator<BlogUser>>[], Func<Scoped, IPasswordValidator<BlogUser>>[], Func<Scoped, UpperInvariantLookupNormalizer>, Func<Scoped, IdentityErrorDescriber>, Scoped, Logger<UserManager<BlogUser>>> , Scoped )
Singularity.Scoped.GetOrAddScopedInstance<T>(Func<Scoped, T> factory, Type key)
(Closure<Func<Scoped, UserManager<BlogUser>>, HttpContextAccessor, Func<Scoped, UserClaimsPrincipalFactory<BlogUser, BlogRole>>, OptionsManager<IdentityOptions>, Logger<SignInManager<BlogUser>>, AuthenticationSchemeProvider, Func<Scoped, DefaultUserConfirmation<BlogUser>>> , Scoped )
Singularity.Scoped.GetOrAddScopedInstance<T>(Func<Scoped, T> factory, Type key)
(Closure<OptionsManager<SecurityStampValidatorOptions>, Func<Scoped, SignInManager<BlogUser>>, SystemClock, LoggerFactory> , Scoped )
Singularity.Scoped.GetOrAddScopedInstance<T>(Func<Scoped, T> factory, Type key)
Singularity.Container.GetInstance(Type type, Scoped scope)
Singularity.Scoped.System.IServiceProvider.GetService(Type serviceType)
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<T>(IServiceProvider provider)
Microsoft.AspNetCore.Identity.SecurityStampValidator.ValidateAsync<TValidator>(CookieValidatePrincipalContext context)
Microsoft.AspNetCore.Identity.SecurityStampValidator.ValidatePrincipalAsync(CookieValidatePrincipalContext context)
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationEvents.ValidatePrincipal(CookieValidatePrincipalContext context)
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleAuthenticateAsync()
Microsoft.AspNetCore.Authentication.AuthenticationHandler<TOptions>.AuthenticateAsync()
Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, string scheme)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by Barsonax** [comment]
Ah this seems to be a bug that was introduced recently, ironically probably during fixing some nullability issues in Singularity. Should be fixed in #142

**Comment by Olbrasoft** [comment]
thank you when the new package will be published ?

**Comment by Barsonax** [comment]
Fixed in #142
